### ISSUE TITLE
Ruth RC#3 needs further testing.

### ISSUE THREAD

**Issue by ingen-lab** [ingen-lab/Ruth#29]
Under the directory _Ruth/Mesh/Avatar Ruth/Shin Ingen/_ the file  OSRuth2_CurrentRelease_AdaEdit_RC3.blend is what I intend to use for the next release.  This file needs to be tested and errors corrected. I will be traveling the next 4 weeks or so. I will have limited time and access to the source files. If any of the contributors want to tackle the task then do it, if not I will do them when I come back from travel.

1. UVMaps for all parts
2. Edge Connection tested and corrected for visible seam line.
3. Possible vertex weight errors and correction when animated inworld.
4. Alpha cuts and associated textures and UV mapping.
5. Static Alpha cut Doll with hands and feet
6. Alpha HUD adjustments for handling feet & hands.

One issue I see is joining Sundance Haiku's toenails to the feet. Not sure if we can actually join parts of AGPL and parts of another license into one blend file part. Certainly, it is now more complicated than what it was. I have no issues with a different license for your original contributed work but we just need to separate the distributed package. I see them as attachments to the system avatar and not as an attachment to Ruth. It is no different than designing a pair of pants and a top, distributed separately as two separate licensed assets.

**Comment by SundanceHaiku** [comment]
I am slowly making progress on UV mapping Ruth's feet.  As Ada hinted, it's a demanding little project.  I've put in about 10 hours so far, and work on when I get a chance.  Shin, let me know if you have a deadline.  Because of RL work, I'm moving along on this slower than expected.

**Comment by EleniaBoucher** [comment]
I also have some difficulties to move forward because I have some health
concerns and also I stuck a little about feet toenails.
I planned to make separate masks for left and right feet and hands. I think
it's useful for some RP or excentric outfits. For that I need a different
material for right and left. I'm able to do that but the Blender file for
feet with separate toenails is not finished.
I also have some difficulties to move forward because I have some health
concerns and also I stuck a little about feet toenails.
I planned to make separate masks for left and right feet and hands. I think
it's useful for some RP or excentric outfits. For that I need a different
material for right and left. I'm able to do that but the Blender file for
feet with separate toenails is not finished

2018-03-30 5:24 GMT+02:00 Sundance Haiku <notifications@github.com>:

**Comment by SundanceHaiku** [comment]
Elenia, I'm so sorry to hear of your health problems.  May you have a speedy recovery.  Sorry that it's taking so long on the feet UV's.  I'm afraid RL work taking away much of my free time, but I will post a note here when UV maps are ready.

**Comment by SundanceHaiku** [comment]
At this point, I have new UV maps prepared for both sets of feet (flat and high).  I also did some re-working of the UV map of the lower body mesh, and I believe I've cleared up the UV alignment problems that were pointed out on Google+.  

Ada tells me that we might not be using the high feet any more, but just in case, in addition to creating a new UV map, I worked with vertex weighting on the high feet so it is more closely aligned with Ada's most recent weight maps for the flat feet.  I still have a bit more to do on that part of things.

I have an interesting puzzle with the fingernails.  The weighting appears to be working fine in Blender.  If I export them from the RC3 Blender file and bring them in-world, some of vertices are being pull off in different directions.  What is puzzling is that if I export them from the RC1 Blender file, there are no problems.  I can't find any difference in fingernail weighting between the RC1 and RC3 files.  I'll keep working on that, but for the time being, if need be, use the original DAE files (found under the Fingernail Project in my directory).

Toenails are looking good, but I do want to test a bit more in-world.

Shin, it's fine with me if you need to place the toenails in a separate package.  Also, you're certainly welcome to use the original toenails that you created for RC1 if my toenails complicate things too much for you.  That way you can keep everything AGPL.  I do want the Ruth project to be successful, and I don't want to hinder it in any way.   

My preference, of course, is to keep the toenails and fingernails free of cost.  The fingernail HUD particularly needs to be free of cost since I used a modification of Chimera's code that she had released several years ago.  If you can make any arrangements in the project which keep these items free, I would be very appreciative.   If that's not possible, I certainly understand.   If you need to eliminate them, it certainly wouldn't mean that I would stop volunteering for the project.

While my preference is to create items which will be free of cost, I'm happy to assist where I can be help.  I fully understand that the UV mapping and other work that I did for RC3 are under an AGPL license.  

I have created a RC3_Edits directory:  Ruth/Mesh/Avatar Ruth/Sundance Haiku/RC3_Edits.  The Readme file provides details on what changes were made and where.  I have included images for a visual representation of the changes.  As mentioned I still have some loose ends to clear up and am currently working on those.

**Comment by SundanceHaiku** [comment]
Note that I have a new file which supersedes the one mentioned above.  The newest, most up-to-date file is located the following directory: Ruth/Mesh/Avatar Ruth/Sundance Haiku/RC3_Edits/RC3_Final/.  The name of the file is:   Release3_AdaEdit_SundanceEdit_11.blend.  The changes are pretty much the same as described above, but as a supplement to this information, I have also created a post on Google + which provides details including illustrations showing where the alternations were made.
